In [1]:
# import modules
import pandas as pd


C:\Users\LENOVO\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\LENOVO\anaconda3\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\Users\LENOVO\anaconda3\lib\site-packages\numpy\.libs\libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
# reading the file
dataset = pd.read_excel('Placement_Data_Full_Class.csv.xlsx')
dataset

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s   CGPA   degree_t  \
0        1      M  67.00   Others  91.00   Others  Commerce  58.00   Sci&Tech   
1        2      M  79.33  Central  78.33   Others   Science  77.48   Sci&Tech   
2        3      M  65.00  Central  68.00  Central      Arts  64.00  Comm&Mgmt   
3        5      M  85.80  Central  73.60  Central  Commerce  73.30  Comm&Mgmt   
4        8      M  82.00  Central  64.00  Central   Science  66.00   Sci&Tech   
..     ...    ...    ...      ...    ...      ...       ...    ...        ...   
210    199      F  67.00  Central  70.00  Central  Commerce  65.00     Others   
211    202      M  54.20  Central  63.00   Others   Science  58.00  Comm&Mgmt   
212    207      M  41.00  Central  42.00  Central   Science  60.00  Comm&Mgmt   
213    209      F  43.00  Central  60.00   Others   Science  65.00  Comm&Mgmt   
214    215      M  62.00  Central  58.00   Others   Science  53.00  Comm&Mgmt   

    workex  etest_p specialisation  Masters      status  
0       No    55.00         Mkt&HR    58.80      Placed  
1      Yes    86.50        Mkt&Fin    66.28      Placed  
2       No    75.00        Mkt&Fin    57.80      Placed  
3       No    96.80        Mkt&Fin    55.50      Placed  
4      Yes    67.00        Mkt&Fin    62.14      Placed  
..     ...      ...            ...      ...         ...  
210     No    88.00         Mkt&HR    71.96  Not Placed  
211     No    79.00         Mkt&HR    58.44  Not Placed  
212     No    97.00        Mkt&Fin    53.39  Not Placed  
213     No    92.66         Mkt&HR    62.92  Not Placed  
214     No    89.00         Mkt&HR    60.22  Not Placed  

[215 rows x 14 columns]

In [6]:
dataset.info()
# dataset = dataset.drop('sl_no', axis=1)
# Talking about the dataset, it contains the secondary school percentage, higher secondary school percentage, degree percentage, degree, and work experience of students.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   gender          215 non-null    object 
 1   ssc_p           215 non-null    float64
 2   ssc_b           215 non-null    object 
 3   hsc_p           215 non-null    float64
 4   hsc_b           215 non-null    object 
 5   hsc_s           215 non-null    object 
 6   CGPA            215 non-null    float64
 7   degree_t        215 non-null    object 
 8   workex          215 non-null    object 
 9   etest_p         215 non-null    float64
 10  specialisation  215 non-null    object 
 11  Masters         215 non-null    float64
 12  status          215 non-null    object 
dtypes: float64(5), object(8)
memory usage: 22.0+ KB


In [7]:
# catgorising col for further labelling
dataset["gender"] = dataset["gender"].astype('category')
dataset["ssc_b"] = dataset["ssc_b"].astype('category')
dataset["hsc_b"] = dataset["hsc_b"].astype('category')
dataset["degree_t"] = dataset["degree_t"].astype('category')
dataset["workex"] = dataset["workex"].astype('category')
dataset["specialisation"] = dataset["specialisation"].astype('category')
dataset["status"] = dataset["status"].astype('category')
dataset["hsc_s"] = dataset["hsc_s"].astype('category')
dataset.dtypes

gender            category
ssc_p              float64
ssc_b             category
hsc_p              float64
hsc_b             category
hsc_s             category
CGPA               float64
degree_t          category
workex            category
etest_p            float64
specialisation    category
Masters            float64
status            category
dtype: object

In [8]:
# labelling the columns
dataset["gender"] = dataset["gender"].cat.codes
dataset["ssc_b"] = dataset["ssc_b"].cat.codes
dataset["hsc_b"] = dataset["hsc_b"].cat.codes
dataset["degree_t"] = dataset["degree_t"].cat.codes
dataset["workex"] = dataset["workex"].cat.codes
dataset["specialisation"] = dataset["specialisation"].cat.codes
dataset["status"] = dataset["status"].cat.codes
dataset["hsc_s"] = dataset["hsc_s"].cat.codes
 
# display dataset
dataset

gender  ssc_p  ssc_b  hsc_p  hsc_b  hsc_s   CGPA  degree_t  workex  \
0         1  67.00      1  91.00      1      1  58.00         2       0   
1         1  79.33      0  78.33      1      2  77.48         2       1   
2         1  65.00      0  68.00      0      0  64.00         0       0   
3         1  85.80      0  73.60      0      1  73.30         0       0   
4         1  82.00      0  64.00      0      2  66.00         2       1   
..      ...    ...    ...    ...    ...    ...    ...       ...     ...   
210       0  67.00      0  70.00      0      1  65.00         1       0   
211       1  54.20      0  63.00      1      2  58.00         0       0   
212       1  41.00      0  42.00      0      2  60.00         0       0   
213       0  43.00      0  60.00      1      2  65.00         0       0   
214       1  62.00      0  58.00      1      2  53.00         0       0   

     etest_p  specialisation  Masters  status  
0      55.00               1    58.80       1  
1      86.50               0    66.28       1  
2      75.00               0    57.80       1  
3      96.80               0    55.50       1  
4      67.00               0    62.14       1  
..       ...             ...      ...     ...  
210    88.00               1    71.96       0  
211    79.00               1    58.44       0  
212    97.00               0    53.39       0  
213    92.66               1    62.92       0  
214    89.00               1    60.22       0  

[215 rows x 13 columns]

In [9]:
# selecting the features and labels
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values
 
# display dependent variables
Y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [10]:
# dividing the data into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y,
                                                    test_size=0.2)
 
# display dataset
dataset.head()

C:\Users\LENOVO\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


gender  ssc_p  ssc_b  hsc_p  hsc_b  hsc_s   CGPA  degree_t  workex  \
0       1  67.00      1  91.00      1      1  58.00         2       0   
1       1  79.33      0  78.33      1      2  77.48         2       1   
2       1  65.00      0  68.00      0      0  64.00         0       0   
3       1  85.80      0  73.60      0      1  73.30         0       0   
4       1  82.00      0  64.00      0      2  66.00         2       1   

   etest_p  specialisation  Masters  status  
0     55.0               1    58.80       1  
1     86.5               0    66.28       1  
2     75.0               0    57.80       1  
3     96.8               0    55.50       1  
4     67.0               0    62.14       1

In [11]:
# creating a classifier using sklearn
from sklearn.linear_model import LogisticRegression
 
clf = LogisticRegression().fit(X_train,Y_train)
# printing the acc
clf.score(X_test, Y_test)

C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.813953488372093

In [12]:
clf.predict([[0, 87, 0, 95, 0, 2, 78, 2, 0, 0, 1, 0]])

array([1], dtype=int8)

In [13]:
# creating a Y_pred for test data
Y_pred = clf.predict(X_test)
 
# display predicted values
Y_pred

array([1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1],
      dtype=int8)

In [14]:
# evaluation of the classifier
from sklearn.metrics import confusion_matrix, accuracy_score
 
# display confusion matrix
print(confusion_matrix(Y_test, Y_pred))
 
# display accuracy
print(accuracy_score(Y_test, Y_pred))

[[ 7  3]
 [ 5 28]]
0.813953488372093


In [15]:
def prediction(gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,CGPA,degree_t,workex,etest_p,specialisation,Masters):
    input1=input2=input3=input4=input5=input6=input7=0
    if gender=="Male":
        input1=1
    else:
        input1=0
    if ssc_b=="Central":
        input2=0
    else:
        input2=1
    if hsc_b=="Central":
        input3=0
    else:
        input3=1
    if hsc_s=="Arts":
        input4=0
    elif hsc_s=="Commerce":
        input4=1
    else:
        input4=2
    if degree_t=="Comm & Mgmt":
        input5=0
    elif degree_t=="Others":
        input5=1
    else:
        input5=2
    if workex=="Yes":
        input6=1
    else:
        input6=0
    if specialisation=="Mkt & Fin":
        input7=0
    else:
        input7=1
    
    pred= clf.predict([[input1,ssc_p,input2,hsc_p,input3,input4,CGPA,input5,
                         input6,etest_p,input7,Masters]])
    if pred==1:
        return "Placed"
    return "Not Placed"

prediction(0, 87, 0, 95, 0, 2, 78, 2, 0, 0, 1, 0)

'Placed'

In [16]:
import gradio as gr
input1 = gr.Radio(["Male","Female"])
input2 = gr.inputs.Number()
input3 = gr.Radio(["Central","Others"])
input4 = gr.inputs.Number()
input5 = gr.Radio(["Central","Others"])
input6 = gr.inputs.Radio(["Arts","Commerce","Science"])
input7 = gr.inputs.Number()
input8 = gr.Radio(["Comm & Mgmt", "Others", "Sci & Tech"])
input9 = gr.Radio(["Yes","No"])
input10 = gr.inputs.Number()
input11 = gr.Radio(["Mkt & Fin","Mkt & HR"])
input12 = gr.inputs.Number()

clf.predict([[ 1,   51.57,  1,   74.66,  1,    1,   59.9,   0,    1,   56.15,  1,   65.99]])

# [ 1.   51.57  1.   74.66  1.    1.   59.9   0.    1.   56.15  1.   65.99]

C:\Users\LENOVO\anaconda3\lib\site-packages\gradio\inputs.py:58: UserWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  warnings.warn(
C:\Users\LENOVO\anaconda3\lib\site-packages\gradio\deprecation.py:40: UserWarning: `optional` parameter is deprecated, and it has no effect
  warnings.warn(value)
C:\Users\LENOVO\anaconda3\lib\site-packages\gradio\inputs.py:182: UserWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  warnings.warn(


array([0], dtype=int8)

In [17]:
gui = gr.Interface(fn=prediction,inputs=[input1, input2,input3,input4,input5,input6,input7,input8,input9,input10,input11,input12],outputs="text")

gui.launch(share=True)

Running on local URL:  http://127.0.0.1:7860
Running on public URL: https://d8741c556c060bd0.gradio.app

This share link expires in 72 hours. For free permanent hosting, check out Spaces: https://www.huggingface.co/spaces


(<gradio.routes.App at 0x1e367717dc0>,
 'http://127.0.0.1:7860/',
 'https://d8741c556c060bd0.gradio.app')